version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_neuromotion
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: .
    container_name: springboot_neuromotion
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/neuromotiondb
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure

volumes:
  mongo_data:
